// <auto-generated />
namespace Tests.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateSongs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateSongs));
        
        string IMigrationMetadata.Id
        {
            get { return "201212122023585_CreateSongs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
